ref: object patcher and patch collector
flant/shell-operator pull request #308
Opened 2021-07-26 20:00 UTC by diafour

#### Overview

- add ignoreIfMissing option for patch operations
- refactor object patcher and patch collector for simpler use In Go hooks

#### What this PR does / why we need it

#### Special notes for your reviewer

#### Does this PR introduce a user-facing change?

```release-note

```

2021-07-26 20:06 UTC, diafour commented on pkg/kube/object_patch/operation.go
> +		//)
PatchCollector was able to return an error if the patch is not valid. Now, PatchCollector saves the patch as-is. Patch content is handled by the ObjectPatcher during ExecuteOperations after hook execution.

2021-07-26 20:08 UTC, diafour commented on pkg/kube/object_patch/operation.go
> +func NewFilterPatchOperation(filter func(*unstructured.Unstructured) (*unstructured.Unstructured, error), apiVersion, kind, namespace, name string, options ...OperationOption) *Operation {
There is no NewJQPatchOperation. JQPatch is now available for shell hooks and not available for Go hooks.

2021-07-26 20:09 UTC, diafour commented on pkg/kube/object_patch/options.go
> +func UseFilterFunc(filterFunc func(*unstructured.Unstructured) (*unstructured.Unstructured, error)) OperationOption {
Oops. I should get rid of these methods.

2021-07-27 06:03 UTC, diafour commented on pkg/kube/object_patch/patch_collector.go
> +	dop.patchOperations = append(dop.patchOperations, NewFilterPatchOperation(filterFunc, apiVersion, kind, namespace, name, options...))
should use `dop.add`

2021-07-27 11:38 UTC, yalosev requested changes
Don't you want to separate CreateOptions/DeleteOptions/UpdateOptions. It will make func signatures more obvious

2021-07-27 16:08 UTC, diafour commented
> Don't you want to separate CreateOptions/DeleteOptions/UpdateOptions. It will make func signatures more obvious

Done!

2021-07-27 18:14 UTC, yalosev approved these changes
LGTM

2021-08-17 10:20 UTC, merged

2021-08-17 10:20 UTC, diafour commented
Approved in deckhouse.