fix: restore exponential backoff after #388
flant/shell-operator pull request #407
Opened 2022-06-15 09:01 UTC by diafour

#### Overview

Restore exponential backoff for delayed between  failed hooks restarts.

#### What this PR does / why we need it

Failed hook restarts every second after merging #388.

#### Special notes for your reviewer

#### Does this PR introduce a user-facing change?

```release-note

```

2022-06-16 07:37 UTC, yalosev approved these changes

2022-06-16 12:09 UTC, nabokihms requested changes
I would like to see a test for the backoff feature because otherwise, we may lose it again during one of the future refactorings.

2022-06-19 11:29 UTC, diafour commented
Added tests for exponential delaying and for CancelTaskDelay.

2022-06-20 09:18 UTC, yalosev approved these changes

2022-06-20 11:55 UTC, merged